@startuml
left to right direction
:Ciudadano Extranjero: as ciuext
actor Ciudadano as ciu
(Registrar entrada) as Re
(Tomar huellas) as Th

ciu -- Re
ciuext -- Th
Re <.. Th : <<extend>>
ciuext --|> ciu
@enduml