@startuml
left to right direction
:new Actor: as nA
(Identificarse) as Id
(Pagar) as pag

nA -- Id
nA -- pag
nA -- (Elegir mensajero)
nA -- (Confirmar)
Id <.. (Registrarse) : <<extend>>
pag <|-- (Pagar con tarjeta)
pag <|-- (Pagar con transferencia)
@enduml