@startuml
left to right direction
actor Cliente as cl

(Confirmar pedido) as Cp
(Cancelar pedido) as Cap
(Devolver cambio) as Dc

cl -- Cp
cl -- Cap
Cp ..> Dc : <<include>>
Cap ..> Dc : <<include>>
@enduml